version: '2.4'
services:
    redis:
        image: redis:alpine
        container_name: redis

    db:
        image: mysql:8.0
        container_name: mysql8
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore
        volumes:
            - pimcore-mysql:/var/lib/mysql
        command: '--default-authentication-plugin=mysql_native_password'
        ports:
            - 3306:3306
            
    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8080:8080

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www/html:ro
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm
            - php-fpm-debug

    php-fpm:
        #user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:PHP8.0-fpm
        container_name: php-fpm
        environment:
            - COMPOSER_HOME=/var/www/html
        depends_on:
            - db
        volumes:
            - .:/var/www/html:cached
            - pimcore-tmp-storage:/tmp:cached

    php-fpm-debug:
        #user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:PHP8.0-fpm-debug
        container_name: php-fpm-debug
        depends_on:
            - db
        volumes:
            - .:/var/www/html:cached
            - pimcore-tmp-storage:/tmp:cached
        environment:
            - PHP_IDE_CONFIG="serverName=localhost"
            - COMPOSER_HOME=/var/www/html

    supervisord:
        #user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:supervisord
        container_name: supervisord
        depends_on:
            - db
        volumes:
            - .:/var/www/html:cached
            - ./.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro

volumes:
    pimcore-mysql:
    pimcore-tmp-storage:
